// status: 1 = Em progresso, 2 = Concluído, 3 = Pausado

export default [
  {
    imgProject: 'src/assets/projects/plataforma_cpid.webp',
    altText: 'Imagem do site Plataforma CPID',
    projectName: 'projects.plataformaCpid.name',
    projectDescription: 'projects.plataformaCpid.description',
    projectLink: 'https://plataformacpid.com.br/',
    hasLinkCode: false,
    status: 1,
    stacks: ['Vue', 'Quasar', 'Python', 'MySQL'],
  },
  {
    imgProject: 'src/assets/projects/projeto_roda_da_vida.webp',
    altText: 'Roda da Vida',
    projectName: 'projects.rodaDaVida.name',
    projectDescription: 'projects.rodaDaVida.description',
    projectLink: 'https://projeto-roda-da-vida.vercel.app/',
    hasLinkCode: false,
    status: 2,
    stacks: ['HTML', 'CSS', 'JavaScript', 'Firebase'],
  },
  {
    imgProject: 'src/assets/projects/beija_flor.webp',
    altText: 'Beija-Flor se alimentando na garrafa',
    projectName: 'projects.redeBeijaFlor.name',
    projectDescription: 'projects.redeBeijaFlor.description',
    projectLink: 'https://app1.arandu.org.br/',
    hasLinkCode: false,
    status: 1,
    stacks: ['Vue', 'Quasar'],
  },
  {
    imgProject: 'src/assets/projects/jogo_da_memoria.webp',
    altText: 'Jogo da Memória versão 8 bits',
    projectName: 'projects.memoryGame.name',
    projectDescription: 'projects.memoryGame.description',
    projectLink: 'https://jogo-da-memoria-2-nu.vercel.app/',
    codeLink: 'https://github.com/LeonardoS1lva/jogo-da-memoria-2',
    status: 2,
    stacks: ['Vue', 'Quasar'],
  },
  {
    imgProject: 'src/assets/projects/calculadora_carrinho_de_compras.webp',
    altText: 'Calculadora de produtos em um carrinho de compras',
    projectName: 'projects.cartShoppingCalculator.name',
    projectDescription: 'projects.cartShoppingCalculator.description',
    projectLink: 'https://calculadora-carrinho-de-compras.vercel.app/',
    hasLinkCode: false,
    status: 2,
    stacks: ['Vue', 'Quasar'],
  },
  {
    imgProject: 'src/assets/projects/lista_de_tarefas_pwa.webp',
    altText: 'Lista de Tarefas',
    projectName: 'projects.taskListPWA.name',
    projectDescription: 'projects.taskListPWA.description',
    projectLink: 'https://play.google.com/store/apps/details?id=app.vercel.crud_pwa_beta.twa',
    hasLinkCode: false,
    status: 2,
    stacks: ['Vue', 'Quasar', 'PWA'],
  },
  {
    imgProject: 'src/assets/projects/to_do_react.webp',
    altText: 'Lista de Tarefas em React',
    projectName: 'projects.toDoReact.name',
    projectDescription: 'projects.toDoReact.description',
    projectLink: 'https://to-do-react-liard-chi.vercel.app/',
    codeLink: 'https://github.com/LeonardoS1lva/to-do-react',
    status: 2,
    stacks: ['React'],
  },
  {
    imgProject: 'src/assets/projects/portfolio_v1.webp',
    altText: 'Primeira versão do meu portfólio',
    projectName: 'projects.portfolioV1.name',
    projectDescription: 'projects.portfolioV1.description',
    projectLink: 'https://leonardos1lva.github.io/portfolio/',
    codeLink: 'https://github.com/LeonardoS1lva/portfolio',
    status: 2,
    stacks: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    imgProject: 'src/assets/projects/advice_generator.webp',
    altText: 'Gerador de Conselhos',
    projectName: 'projects.adviceGenerator.name',
    projectDescription: 'projects.adviceGenerator.description',
    projectLink: 'https://leonardos1lva.github.io/advice-generator-app/',
    codeLink: 'https://github.com/LeonardoS1lva/advice-generator-app',
    status: 2,
    stacks: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    imgProject: 'src/assets/projects/ip_address_tracker.webp',
    altText: 'Rastreador de Endereço IP',
    projectName: 'projects.ipAddressTracker.name',
    projectDescription: 'projects.ipAddressTracker.description',
    projectLink: 'https://leonardos1lva.github.io/ip-address-tracker-master/',
    codeLink: 'https://github.com/LeonardoS1lva/ip-address-tracker-master',
    status: 2,
    stacks: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    imgProject: 'src/assets/projects/weather_test_api.webp',
    altText: 'Aplicação de Previsão do Tempo',
    projectName: 'projects.weatherTestApi.name',
    projectDescription: 'projects.weatherTestApi.description',
    projectLink: 'https://leonardos1lva.github.io/weather-test-api/',
    codeLink: 'https://github.com/LeonardoS1lva/weather-test-api',
    status: 2,
    stacks: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    imgProject: 'src/assets/projects/gerador_de_qrcode.webp',
    altText: 'Gerador de QR Code',
    projectName: 'projects.qrCodeGenerator.name',
    projectDescription: 'projects.qrCodeGenerator.description',
    projectLink: 'https://leonardos1lva.github.io/gerador-de-qrcode/',
    codeLink: 'https://github.com/LeonardoS1lva/gerador-de-qrcode',
    status: 2,
    stacks: ['HTML', 'Bootstrap', 'JavaScript'],
  },
  {
    imgProject: 'src/assets/projects/gerador_de_senhas.webp',
    altText: 'Gerador de Senhas',
    projectName: 'projects.passwordGenerator.name',
    projectDescription: 'projects.passwordGenerator.description',
    projectLink: 'https://leonardos1lva.github.io/Gerador-de-Senhas/',
    codeLink: 'https://github.com/LeonardoS1lva/Gerador-de-Senhas',
    status: 2,
    stacks: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    imgProject: 'src/assets/projects/carrinho_de_compras.webp',
    altText: 'Carrinho de Compras',
    projectName: 'projects.shoppingCart.name',
    projectDescription: 'projects.shoppingCart.description',
    projectLink: 'https://leonardos1lva.github.io/carrinho-de-compras/',
    codeLink: 'https://github.com/LeonardoS1lva/carrinho-de-compras',
    status: 2,
    stacks: ['HTML', 'Tailwind', 'JavaScript'],
  },
]
